[package]
name = "pangolin"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "index"
path = "index/src/main.rs"

[dependencies]
config = "0.14"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
tempfile = "3.10"

[dev-dependencies]
serial_test = "3.0.0"
