[server.api]
name = "Pangolin"
port = 3000

[server.embeddings]
name = "EmbeddingService"
port = 50051
shutdown_period = 5
worker_threads = 10

[transformers]
model_list = ["all-mpnet-base-v2", "all-MiniLM-L6-v2"]

[spacy]
model_list = []
